open System.IO
open Microsoft.FSharp.Core
open System.Collections.Generic
open Microsoft.FSharp.Collections

let lines = File.ReadAllText "./day3/input.txt"
let input:string [] = lines.Split("\r\n")

let items = ['a' .. 'z'] @ ['A' .. 'Z']
let priorityValues = [ 1..52]

let priorities = List.zip items priorityValues

let getValue [key] =
    match priorities |> List.tryFind (fun (k, v) -> k = key) with
    | Some (k, v) -> v
    | None -> failwith "Key not found" // generated by chatGPT

let splitString (toSplit: string) =
    let firstHalf = toSplit.Substring(0, toSplit.Length / 2)
    let secondHalf = toSplit.Substring(toSplit.Length / 2)
    [| firstHalf; secondHalf |]

let commonCharacters (splittedTuple: string[]) =
    let list1 = splittedTuple[0]  |> Seq.toList
    let list2 =  splittedTuple[1] |> Seq.toList
    Set.intersect (Set.ofList list1) (Set.ofList list2) |> Set.toList

// Part 1:
let buggyInput = input
                |> Array.filter(fun x -> x.Length % 2 <> 0)

let splittedTuples = input
                    |> Array.map(fun x -> splitString(x))
                    |> Array.map(fun x -> commonCharacters(x))
                    |> Array.map(fun x -> getValue(x))
                    |> Array.sum

splittedTuples |> printfn "%d"

// Part 2
let commonCharInGroup (group: string list) = 
        let set1 = group[0]  |> Set.ofSeq
        let set2 =  group[1] |> Set.ofSeq
        let set3 =  group[2] |> Set.ofSeq
        set1 |> Set.intersect set2 |> Set.intersect set3 |> Set.toList


let splittedGroupedTuples = input
                            |> Array.chunkBySize 3
                            |> Array.map(fun x -> Seq.toList x)
                            |> Array.map (fun x-> commonCharInGroup(x))
                            |> Array.map(fun x -> getValue(x))
                            |> Array.sum

splittedGroupedTuples |> printfn "%d"